// build-index.mjs가 생성. 프로젝트 목록과 연결 저장소.
export const REGISTRY = [
 {
  "id": "pub-kaes",
  "kind": "pub",
  "name": "Enhancing Korean Automated Essay Scoring via Linguistically Informed Augmentation and Topic-Aware Preprocessing",
  "ko": "",
  "when": "2025 – 2026",
  "url": "https://ghko99.github.io/projects/pub-kaes/",
  "summary": "한국어 자동 에세이 채점은 라벨 데이터가 적고 형태론이 복잡하다는 두 가지 벽에 부딪힙니다.",
  "repos": [
   {
    "name": "Korean-Text-Data-Augmentation",
    "branch": "master",
    "files": [
     "README.md",
     "augmentation.py",
     "dataset_utils.py",
     "docs/model_cache_notes.md",
     "docs/output_filtering.md",
     "docs/quality_checks.md",
     "docs/setup.md",
     "mbart_aug.py",
     "mbart_data.py",
     "mbart_train.py",
     "mlm_augmentation.py",
     "mlm_insert_augmentation.py",
     "mlm_train.py",
     "requirements.txt",
     "save_data.py",
     "sts/base_config.yaml",
     "sts/dataloader.py",
     "sts/lightning_logs/version_0/hparams.yaml",
     "sts/lightning_logs/version_1/hparams.yaml",
     "sts/lightning_logs/version_2/hparams.yaml",
     "sts/lightning_logs/version_3/hparams.yaml",
     "sts/lightning_logs/version_4/hparams.yaml",
     "sts/mbart_config.yaml",
     "sts/model.py",
     "sts/random_masking_insertion_config.yaml",
     "sts/random_masking_replacement_config.yaml",
     "sts/t5_config.yaml",
     "sts/train.py",
     "sts/train.sh",
     "t5_augmentation.py"
    ]
   }
  ]
 },
 {
  "id": "pub-tkips",
  "kind": "pub",
  "name": "다중 목적 학습과 Self-Consistency를 활용한 생성형 LLM의 자동 에세이 채점 성능 최적화",
  "ko": "Optimizing Automated Essay Scoring Performance of Generative LLMs Using Multi-objective Learning and Self-Consistency",
  "when": "2026.05",
  "url": "https://ghko99.github.io/projects/pub-tkips/",
  "summary": "기존 채점 모델은 점수는 잘 맞히지만 피드백을 만들지 못하고, 생성형 LLM은 점수를 텍스트 토큰 으로 다루기 때문에 점수 사이의 순서와 거리를 배우지 못하며 실행할 때마다 결과가 달라집니다.",
  "repos": [
   {
    "name": "lora-self-consistency-aes",
    "branch": "main",
    "files": [
     "README.md",
     "docs/generation_audit.md",
     "docs/run_tracking.md",
     "docs/self_consistency_notes.md",
     "main_pipeline.py",
     "modules/aes_dataloader.py",
     "modules/class_balanced_focal_loss.py",
     "modules/custom_trainer.py",
     "modules/evaluate_module.py",
     "modules/inference_module.py",
     "modules/number_token_loss.py",
     "modules/number_tokenizer.py",
     "modules/train_module.py",
     "modules/wasserstein_number_token_loss.py",
     "requirements.txt",
     "run_consistency_kanana_wntl.sh",
     "run_consistency_ntl_emo_wntl.sh",
     "self_consistency.py"
    ]
   }
  ],
  "pdf": "https://ghko99.github.io/papers/pub-tkips.pdf"
 },
 {
  "id": "pub-feak",
  "kind": "pub",
  "name": "From Evaluation to Feedback: A Feature-Based and LLM-Constrained Tool for Korean Writing Assessment",
  "ko": "",
  "when": "2026.03",
  "url": "https://ghko99.github.io/projects/pub-feak/",
  "summary": "기존 자동 평가는 점수는 정확하지만 무엇을 고쳐야 하는지 말해주지 못하고, 범용 LLM은 설명은 유창하지만 환각과 정보 과부하가 따릅니다.",
  "repos": [],
  "pdf": "https://ghko99.github.io/papers/pub-feak.pdf"
 },
 {
  "id": "pub-ukta",
  "kind": "pub",
  "name": "UKTA: Unified Korean Text Analyzer",
  "ko": "",
  "when": "2025.03",
  "url": "https://ghko99.github.io/projects/pub-ukta/",
  "summary": "기존 한국어 작문 평가 도구는 한 가지 관점만 보고, 앞 단계의 오류가 뒤로 전파되며, 왜 그 점수인지 설명하지 못했습니다.",
  "repos": [
   {
    "name": "aes-ukta-exp",
    "branch": "main",
    "files": [
     "README.md",
     "config.py",
     "docs/artifact_policy.md",
     "docs/experiment_notes.md",
     "docs/feature_audit.md",
     "embedding.py",
     "hyper_parameter_search.py",
     "kobert_gru_with_features.py",
     "performance.py",
     "requirements.txt"
    ]
   }
  ],
  "pdf": "https://ghko99.github.io/papers/pub-ukta.pdf"
 },
 {
  "id": "pub-hclt",
  "kind": "pub",
  "name": "에세이 자동 평가 모델 성능 향상을 위한 데이터 증강과 전처리",
  "ko": "",
  "when": "2023.10",
  "url": "https://ghko99.github.io/projects/pub-hclt/",
  "summary": "KCC 2023에서 주제 정보가 채점에 도움이 된다는 것을 확인한 뒤, 데이터의 품질과 다양성 자체를 높이는 방법을 찾았습니다.",
  "repos": [
   {
    "name": "Korean-Text-Data-Augmentation",
    "branch": "master",
    "files": [
     "README.md",
     "augmentation.py",
     "dataset_utils.py",
     "docs/model_cache_notes.md",
     "docs/output_filtering.md",
     "docs/quality_checks.md",
     "docs/setup.md",
     "mbart_aug.py",
     "mbart_data.py",
     "mbart_train.py",
     "mlm_augmentation.py",
     "mlm_insert_augmentation.py",
     "mlm_train.py",
     "requirements.txt",
     "save_data.py",
     "sts/base_config.yaml",
     "sts/dataloader.py",
     "sts/lightning_logs/version_0/hparams.yaml",
     "sts/lightning_logs/version_1/hparams.yaml",
     "sts/lightning_logs/version_2/hparams.yaml",
     "sts/lightning_logs/version_3/hparams.yaml",
     "sts/lightning_logs/version_4/hparams.yaml",
     "sts/mbart_config.yaml",
     "sts/model.py",
     "sts/random_masking_insertion_config.yaml",
     "sts/random_masking_replacement_config.yaml",
     "sts/t5_config.yaml",
     "sts/train.py",
     "sts/train.sh",
     "t5_augmentation.py"
    ]
   }
  ],
  "pdf": "https://ghko99.github.io/papers/pub-hclt.pdf"
 },
 {
  "id": "pub-kcc",
  "kind": "pub",
  "name": "데이터 증강을 이용한 KoBERT 기반 에세이 자동 평가 성능 향상",
  "ko": "",
  "when": "2023.06",
  "url": "https://ghko99.github.io/projects/pub-kcc/",
  "summary": "글의 Topic과 Type 정보를 데이터에 삽입하는 증강으로 KoBERT 채점기의 일치도를 한 단계 끌어올린 첫 연구입니다.",
  "repos": [
   {
    "name": "aes_data_augment",
    "branch": "master",
    "files": [
     "README.md",
     "aes_embedding.py",
     "aes_train.py",
     "docs/augmentation_tracking.md",
     "docs/evaluation_protocol.md",
     "docs/reproducibility.md",
     "requirements.txt",
     "tokenization_kobert.py"
    ]
   }
  ],
  "pdf": "https://ghko99.github.io/papers/pub-kcc.pdf"
 },
 {
  "id": "pub-thesis",
  "kind": "pub",
  "name": "생성형 대규모 언어모델 기반 한국어 자동 에세이 채점 성능 개선 연구",
  "ko": "",
  "when": "2026.08",
  "url": "https://ghko99.github.io/projects/pub-thesis/",
  "summary": "판별 모델은 점수만 내고, 생성형 LLM은 점수와 피드백을 함께 내지만 정확도와 재현성이 낮습니다.",
  "repos": [
   {
    "name": "essay-agent",
    "branch": "main",
    "files": [
     "README.md",
     "backend/__init__.py",
     "backend/agent.py",
     "backend/main.py",
     "backend/model.py",
     "backend/prompt.py",
     "backend/rubric.py",
     "backend/score_percentiles.py",
     "backend/scoring_rules.py",
     "backend/tools/__init__.py",
     "backend/tools/_common.py",
     "backend/tools/keyword_coverage.py",
     "backend/tools/lexical_grounding.py",
     "backend/tools/linguistic_analysis.py",
     "backend/tools/norm_lookup.py",
     "backend/tools/orthography_probe.py",
     "backend/tools/rubric_retrieve.py",
     "backend/tools/terminology_grounding.py",
     "backend/topics.py",
     "frontend/app.js",
     "frontend/index.html",
     "frontend/robots.txt",
     "requirements.txt",
     "run.sh"
    ]
   },
   {
    "name": "aes-llm-training",
    "branch": "main",
    "files": [
     "README.md",
     "collator.py",
     "docs/checkpoint_selection.md",
     "docs/evaluation_notes.md",
     "docs/prediction_audit.md",
     "docs/release_checklist.md",
     "docs/run_tracking.md",
     "evaluate.py",
     "inference.py",
     "number_token_loss.py",
     "number_tokenizer.py",
     "requirements.txt",
     "train.py",
     "train.sh",
     "train_multi_gpu.sh",
     "trainer.py"
    ]
   },
   {
    "name": "essay_scoring_llm",
    "branch": "main",
    "files": [
     "README.md",
     "assets/adapter/README.md",
     "assets/adapter/chat_template.jinja",
     "docs/OUTPUT_SCHEMA.md",
     "essay_scoring_llm/__init__.py",
     "essay_scoring_llm/__main__.py",
     "essay_scoring_llm/baseline.py",
     "essay_scoring_llm/batch.py",
     "essay_scoring_llm/cache.py",
     "essay_scoring_llm/cli.py",
     "essay_scoring_llm/config.py",
     "essay_scoring_llm/correction.py",
     "essay_scoring_llm/dataset.py",
     "essay_scoring_llm/experiment.py",
     "essay_scoring_llm/feak.py",
     "essay_scoring_llm/feak_feature/README.md",
     "essay_scoring_llm/feak_feature/__init__.py",
     "essay_scoring_llm/feak_feature/feak_feature.py",
     "essay_scoring_llm/feak_feature/korcat_core/apps/morph/bareun.py",
     "essay_scoring_llm/feak_feature/korcat_core/apps/morph/morph.py",
     "essay_scoring_llm/feak_feature/korcat_core/apps/morph/utagger.py",
     "essay_scoring_llm/feak_feature/requirements.txt",
     "essay_scoring_llm/feak_feature/sample_essay.txt",
     "essay_scoring_llm/feak_feature/test_features.py",
     "essay_scoring_llm/number_tokenizer.py",
     "essay_scoring_llm/qwk.py",
     "essay_scoring_llm/rounder.py",
     "essay_scoring_llm/rubrics.py",
     "essay_scoring_llm/scaling.py",
     "essay_scoring_llm/schema.py",
     "essay_scoring_llm/single.py",
     "essay_scoring_llm/soft_sc.py",
     "essay_scoring_llm/visualize.py",
     "pyproject.toml",
     "requirements-live.txt",
     "requirements.txt",
     "tests/test_smoke.py"
    ]
   },
   {
    "name": "kanana-wntl-14all-strategy-comparison",
    "branch": "main",
    "files": [
     "README.md",
     "compare_14_all_inference_strategies.py",
     "kanana_wntl_20260407_002343/README.md",
     "kanana_wntl_20260407_002343/chat_template.jinja",
     "modules/inference_module.py",
     "modules/number_tokenizer.py",
     "requirements.txt",
     "run_14_all_strategy_comparison.sh",
     "weighted_digit_inference.py"
    ]
   }
  ]
 },
 {
  "id": "proj-geulgyeol",
  "kind": "proj",
  "name": "글결",
  "ko": "근거 기반 한국어 에세이 자동 채점 Agent",
  "when": "2026.03 – 06",
  "url": "https://ghko99.github.io/projects/proj-geulgyeol/",
  "summary": "점수뿐 아니라 피드백과 객관적인 채점 근거 를 함께 제시하는 LLM Agent입니다.",
  "repos": [
   {
    "name": "essay-agent",
    "branch": "main",
    "files": [
     "README.md",
     "backend/__init__.py",
     "backend/agent.py",
     "backend/main.py",
     "backend/model.py",
     "backend/prompt.py",
     "backend/rubric.py",
     "backend/score_percentiles.py",
     "backend/scoring_rules.py",
     "backend/tools/__init__.py",
     "backend/tools/_common.py",
     "backend/tools/keyword_coverage.py",
     "backend/tools/lexical_grounding.py",
     "backend/tools/linguistic_analysis.py",
     "backend/tools/norm_lookup.py",
     "backend/tools/orthography_probe.py",
     "backend/tools/rubric_retrieve.py",
     "backend/tools/terminology_grounding.py",
     "backend/topics.py",
     "frontend/app.js",
     "frontend/index.html",
     "frontend/robots.txt",
     "requirements.txt",
     "run.sh"
    ]
   },
   {
    "name": "essay_scoring_llm",
    "branch": "main",
    "files": [
     "README.md",
     "assets/adapter/README.md",
     "assets/adapter/chat_template.jinja",
     "docs/OUTPUT_SCHEMA.md",
     "essay_scoring_llm/__init__.py",
     "essay_scoring_llm/__main__.py",
     "essay_scoring_llm/baseline.py",
     "essay_scoring_llm/batch.py",
     "essay_scoring_llm/cache.py",
     "essay_scoring_llm/cli.py",
     "essay_scoring_llm/config.py",
     "essay_scoring_llm/correction.py",
     "essay_scoring_llm/dataset.py",
     "essay_scoring_llm/experiment.py",
     "essay_scoring_llm/feak.py",
     "essay_scoring_llm/feak_feature/README.md",
     "essay_scoring_llm/feak_feature/__init__.py",
     "essay_scoring_llm/feak_feature/feak_feature.py",
     "essay_scoring_llm/feak_feature/korcat_core/apps/morph/bareun.py",
     "essay_scoring_llm/feak_feature/korcat_core/apps/morph/morph.py",
     "essay_scoring_llm/feak_feature/korcat_core/apps/morph/utagger.py",
     "essay_scoring_llm/feak_feature/requirements.txt",
     "essay_scoring_llm/feak_feature/sample_essay.txt",
     "essay_scoring_llm/feak_feature/test_features.py",
     "essay_scoring_llm/number_tokenizer.py",
     "essay_scoring_llm/qwk.py",
     "essay_scoring_llm/rounder.py",
     "essay_scoring_llm/rubrics.py",
     "essay_scoring_llm/scaling.py",
     "essay_scoring_llm/schema.py",
     "essay_scoring_llm/single.py",
     "essay_scoring_llm/soft_sc.py",
     "essay_scoring_llm/visualize.py",
     "pyproject.toml",
     "requirements-live.txt",
     "requirements.txt",
     "tests/test_smoke.py"
    ]
   }
  ]
 },
 {
  "id": "proj-lh",
  "kind": "proj",
  "name": "LH 청약 추천 및 챗봇",
  "ko": "제1회 AI반도체 기술인재 선발대회 · sLLM/sLM 분야 · 수요기업 리벨리온",
  "when": "2024.08 – 12",
  "url": "https://ghko99.github.io/projects/proj-lh/",
  "summary": "청약 통장 가입자는 늘고 있지만 청약 절차와 20페이지가 넘는 공고문은 이해하기 어렵습니다.",
  "repos": [
   {
    "name": "aichipcon_AIF_sLLM",
    "branch": "main",
    "files": [
     "LHAPI/collect_DATA/api_request_specific.js",
     "LHAPI/collect_DATA/deduplicate_specific_csv.js",
     "LHAPI/collect_DATA/download_PDFs_공고중.js",
     "LHAPI/search_API/search_python.py",
     "README.md",
     "ai/model/__init__.py",
     "ai/model/chatbot_model.py",
     "ai/model/ex.py",
     "ai/model/exex.py",
     "ai/model/rag_generator.py",
     "ai/model/rag_retriever.py",
     "ai/model/survey_model.py",
     "backend/app.py",
     "backend/app_flask.py",
     "backend/chatbot/__init__.py",
     "backend/chatbot/chatbot.py",
     "backend/search/search.py",
     "backend/search/search_2.py",
     "backend/search/search_3.py",
     "backend/search/search_engine.ipynb",
     "docs/data_pipeline_notes.md",
     "docs/deployment_runbook.md",
     "docs/local_setup.md",
     "docs/monitoring_notes.md",
     "docs/rag_evaluation_notes.md",
     "frontend/README.md",
     "frontend/app/chatbot/Chatbot.tsx",
     "frontend/app/chatbot/page.tsx",
     "frontend/app/dashboard/page.tsx",
     "frontend/app/ex/page.tsx",
     "frontend/app/intro/page.tsx",
     "frontend/app/layout.tsx",
     "frontend/app/page.tsx",
     "frontend/app/survey/page.tsx",
     "frontend/components/AgeSelector.tsx",
     "frontend/components/DetailedFilters.tsx",
     "frontend/components/DetailedSearchForm.tsx",
     "frontend/components/PDFViewer.tsx",
     "frontend/hooks/use-mobile.tsx",
     "frontend/lib/utils.ts",
     "frontend/public/survey-data.tsx",
     "frontend/tailwind.config.ts",
     "locust/locust.py",
     "script.sh",
     "vllm_backend/.pre-commit-config.yaml",
     "vllm_backend/README.md",
     "vllm_backend/pyproject.toml"
    ]
   }
  ]
 },
 {
  "id": "proj-ukta-proj",
  "kind": "proj",
  "name": "U-KTA",
  "ko": "사용자 중심의 한국어 텍스트 분석 및 설명 가능한 글쓰기 평가 도구",
  "when": "2024.09 – 2026.05",
  "url": "https://ghko99.github.io/projects/proj-ukta-proj/",
  "summary": "교사 한 명이 맡는 학생이 많아 개별 피드백은 물리적으로 어렵고, 기존 AI 채점은 근거가 없는 데다 QWK 0.5 미만이며 학습한 주제에서만 작동합니다.",
  "repos": [
   {
    "name": "aes-ukta-exp",
    "branch": "main",
    "files": [
     "README.md",
     "config.py",
     "docs/artifact_policy.md",
     "docs/experiment_notes.md",
     "docs/feature_audit.md",
     "embedding.py",
     "hyper_parameter_search.py",
     "kobert_gru_with_features.py",
     "performance.py",
     "requirements.txt"
    ]
   }
  ]
 },
 {
  "id": "proj-oem",
  "kind": "proj",
  "name": "화장품 OEM 통합 관리 플랫폼",
  "ko": "LLM으로 비정형 의뢰를 표준 의뢰서로, 규제 정보를 RAG로",
  "when": "2025.04 – 12",
  "url": "https://ghko99.github.io/projects/proj-oem/",
  "summary": "화장품 OEM/ODM 공장에는 손글씨, 엑셀, 한글, PDF 등 형식이 제각각인 의뢰서가 들어오고, 실무자는 이를 매번 옮겨 적어야 합니다.",
  "repos": [
   {
    "name": "cosmetics-oem-erp-prototype",
    "branch": "main",
    "files": [
     "README.md",
     "ai-server/README.md",
     "ai-server/api/ai_endpoints.py",
     "ai-server/api/models_endpoint.py",
     "ai-server/api/product_forms_endpoint.py",
     "ai-server/main.py",
     "ai-server/requirements.txt",
     "ai-server/services/ai_service.py",
     "ai-server/services/product_forms.py",
     "backend/api/admin.py",
     "backend/api/product_form.py",
     "backend/api/requests.py",
     "backend/database.py",
     "backend/main.py",
     "backend/models.py",
     "backend/requirements.txt",
     "backend/schemas.py",
     "backend/services/product_form_service.py",
     "backend/services/product_forms_client.py",
     "docker-compose.yml",
     "frontend/README.md",
     "frontend/app/admin/page.tsx",
     "frontend/app/auto-form/korean/page.tsx",
     "frontend/app/auto-form/page.tsx",
     "frontend/app/layout.tsx",
     "frontend/app/oem-form-test/OEMCosmeticsForm.jsx",
     "frontend/app/oem-form-test/page.jsx",
     "frontend/app/page.tsx",
     "frontend/components/Admin/AdminLayout.tsx",
     "frontend/components/Admin/Header.tsx",
     "frontend/components/Admin/LeftSidebar.tsx",
     "frontend/components/Admin/MainWorkspace.tsx",
     "frontend/components/Admin/RequestDetail.tsx",
     "frontend/components/Admin/RequestList.tsx",
     "frontend/components/Admin/RightSidebar.tsx",
     "frontend/components/Admin/tabs/RequestDetailTab.tsx",
     "frontend/components/Admin/tabs/RequestListTab.tsx",
     "frontend/components/AutoForm/ChatPanel.tsx",
     "frontend/components/AutoForm/FormPanel.tsx",
     "frontend/components/AutoForm/KoreanFormPanel.tsx",
     "frontend/components/AutoForm/ProductSelection.tsx",
     "frontend/components/AutoForm/SubmissionPopup.tsx",
     "frontend/components/theme-provider.tsx",
     "frontend/components/theme-toggle.tsx",
     "frontend/hooks/use-mobile.ts",
     "frontend/hooks/use-toast.ts",
     "frontend/lib/api.ts",
     "frontend/lib/stores/chatStore.ts",
     "frontend/lib/stores/tabStore.ts",
     "frontend/lib/utils.ts",
     "frontend/next.config.ts",
     "llm-product-transfer-form/README.md",
     "llm-product-transfer-form/llm_product_form_gpt.py",
     "llm-product-transfer-form/requirements.txt",
     "llm-test-client.js",
     "run_backend.sh",
     "run_frontend.sh",
     "test_llm_form.py",
     "test_product_form_api.py"
    ]
   }
  ]
 },
 {
  "id": "proj-aihub",
  "kind": "proj",
  "name": "한국어 성능이 개선된 초거대 AI 언어모델 데이터 구축",
  "ko": "20억 어절 말뭉치 · LLaMA 기반 13B/33B/65B 공개",
  "when": "2023.07 – 12",
  "url": "https://ghko99.github.io/projects/proj-aihub/",
  "summary": "기존에 공개된 한국어 데이터는 뉴스와 댓글에 치우쳐 있었고, 고성능 모델과 데이터는 비공개인 경우가 많았습니다.",
  "repos": [
   {
    "name": "Korean-Text-Data-Augmentation",
    "branch": "master",
    "files": [
     "README.md",
     "augmentation.py",
     "dataset_utils.py",
     "docs/model_cache_notes.md",
     "docs/output_filtering.md",
     "docs/quality_checks.md",
     "docs/setup.md",
     "mbart_aug.py",
     "mbart_data.py",
     "mbart_train.py",
     "mlm_augmentation.py",
     "mlm_insert_augmentation.py",
     "mlm_train.py",
     "requirements.txt",
     "save_data.py",
     "sts/base_config.yaml",
     "sts/dataloader.py",
     "sts/lightning_logs/version_0/hparams.yaml",
     "sts/lightning_logs/version_1/hparams.yaml",
     "sts/lightning_logs/version_2/hparams.yaml",
     "sts/lightning_logs/version_3/hparams.yaml",
     "sts/lightning_logs/version_4/hparams.yaml",
     "sts/mbart_config.yaml",
     "sts/model.py",
     "sts/random_masking_insertion_config.yaml",
     "sts/random_masking_replacement_config.yaml",
     "sts/t5_config.yaml",
     "sts/train.py",
     "sts/train.sh",
     "t5_augmentation.py"
    ]
   }
  ]
 },
 {
  "id": "proj-hscode",
  "kind": "proj",
  "name": "HSCODE 자동 추천 시스템",
  "ko": "디지털 포워딩 기업 매칭 앱 InhaTrade",
  "when": "2023.09 – 12",
  "url": "https://ghko99.github.io/projects/proj-hscode/",
  "summary": "수출 기업과 포워딩 기업을 연결하는 모바일 매칭 플랫폼입니다.",
  "repos": [
   {
    "name": "Hscode",
    "branch": "master",
    "files": [
     "README.md",
     "accuracy.py",
     "crawl_data.py",
     "docs/data_contract.md",
     "docs/error_analysis.md",
     "docs/evaluation.md",
     "docs/inference_notes.md",
     "docs/setup.md",
     "embedding.py",
     "preprocess.py",
     "recommend.py",
     "requirements.txt",
     "train_test_split.py"
    ]
   }
  ]
 },
 {
  "id": "act-naeultech",
  "kind": "act",
  "name": "딥러닝 기반 모호성 분석 및 비식별화 모듈 개발 (YM-나을텍 용역과제)",
  "ko": "",
  "when": "2026.03.01 – 2026.09.19",
  "url": "https://ghko99.github.io/cv/",
  "summary": "판결문 도메인의 정보 추출과 개인정보·민감정보 비식별화를 두 단계로 수행한 YM-나을텍 용역과제. 1단계 판결문 정보 추출(Macro F1 0.9791), 2단계 비식별화 모듈 개발.",
  "repos": []
 },
 {
  "id": "act-venture-academy",
  "kind": "act",
  "name": "인하대학교 벤처스타트업 아카데미 1기",
  "ko": "",
  "when": "2023.02.28 – 2024.02.16",
  "url": "https://ghko99.github.io/cv/",
  "summary": "중소벤처기업부 주관 SW 인재양성 프로그램. 알고리즘·자료구조·코딩테스트 문제 해결 역량을 약 1년간 훈련하고 온라인 코딩캠프 5회를 이수해 수료.",
  "repos": []
 },
 {
  "id": "act-vip",
  "kind": "act",
  "name": "다학년 연구프로젝트(VIP) — ERP-42 mini 자율주행 차량 구동 프로젝트",
  "ko": "",
  "when": "2022.03.02 – 2022.06.20",
  "url": "https://ghko99.github.io/cv/",
  "summary": "학년과 전공이 다른 8인 팀이 ERP-42 mini 플랫폼으로 승객 감지부터 목적지 이송까지의 자율주행 시나리오를 구현하고 실차 검증한 학부 교과 프로젝트. Planning 파트 담당.",
  "repos": []
 },
 {
  "id": "act-iitp-multimodal",
  "kind": "act",
  "name": "산업융합형 멀티모달 생성 인공지능 인재양성 (IITP 생성AI 선도인재양성 사업)",
  "ko": "",
  "when": "2025.07.03 – 2025.10.31 (본인 참여 기간)",
  "url": "https://ghko99.github.io/cv/",
  "summary": "과기정통부·IITP의 생성AI 선도인재양성 사업. 포티투마루가 주관하고 인하대·성균관대·부산대·UNIST가 참여하며, 인하대는 생성 AI 기반 물류 혁신 솔루션을 주제로 함. 본인은 2025.07–10 참여 연구원으로 보고서 자동 생성 부분을 담당함. 그 외 세부 산출물·수치는 기록돼 있지 않음.",
  "repos": []
 }
];
